// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
// import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };
// const ibmSans = IBM_Plex_Sans({
//   subsets: ["latin"],
//   variable: "--font-ibm-sans",
//   weight: ["300", "400", "500", "600", "700"], // Choose what you need
//   display: "swap",
// });

// const ibmMono = IBM_Plex_Mono({
//   subsets: ["latin"],
//   variable: "--font-ibm-mono",
//   weight: ["400", "500", "700"],
//   display: "swap",
// });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${ibmSans.variable} ${ibmMono.variable}`}>{children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/molecule/navbar";

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Specify the weights you need
  variable: "--font-ibm-plex-sans",
});

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Using IBM Plex Sans",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${ibmPlexSans.className} ${ibmPlexSans.variable}`}>
      <body>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
