#The TimeZone is in the following format to check if the time had DST [H,M,Boolean]
COUNTRIES = {
    "AFGHANISTAN": [4, 30, False],
    "ALBANIA": [1, 0, True],
    "ALGERIA": [1, 0, False],
    "ANDORRA": [1, 0, True],
    "ANGOLA": [1, 0, False],
    "ARGENTINA": [-3, 0, False],
    "ARMENIA": [4, 0, False],
    "AUSTRALIA": [10, 0, True],
    "AUSTRIA": [1, 0, True],
    "AZERBAIJAN": [4, 0, False],
    "BAHRAIN": [3, 0, False],
    "BANGLADESH": [6, 0, False],
    "BELARUS": [3, 0, False],
    "BELGIUM": [1, 0, True],
    "BELIZE": [-6, 0, False],
    "BENIN": [1, 0, False],
    "BHUTAN": [6, 0, False],
    "BOLIVIA": [-4, 0, False],
    "BOSNIA AND HERZEGOVINA": [1, 0, True],
    "BOTSWANA": [2, 0, False],
    "BRAZIL": [-3, 0, False],
    "BRUNEI": [8, 0, False],
    "BULGARIA": [2, 0, True],
    "BURKINA FASO": [0, 0, False],
    "BURUNDI": [2, 0, False],
    "CAMBODIA": [7, 0, False],
    "CAMEROON": [1, 0, False],
    "CANADA": [-5, 0, True],
    "CHAD": [1, 0, False],
    "CHILE": [-4, 0, False],
    "CHINA": [8, 0, False],
    "COLOMBIA": [-5, 0, False],
    "CONGO (DRC)": [2, 0, False],
    "CONGO (REPUBLIC)": [1, 0, False],
    "COSTA RICA": [-6, 0, False],
    "CROATIA": [1, 0, True],
    "CUBA": [-5, 0, True],
    "CYPRUS": [2, 0, True],
    "CZECH REPUBLIC": [1, 0, True],
    "DENMARK": [1, 0, True],
    "DJIBOUTI": [3, 0, False],
    "DOMINICAN REPUBLIC": [-4, 0, False],
    "ECUADOR": [-5, 0, False],
    "EGYPT": [2, 0, False],
    "EL SALVADOR": [-6, 0, False],
    "ESTONIA": [2, 0, True],
    "ETHIOPIA": [3, 0, False],
    "FIJI": [12, 0, False],
    "FINLAND": [2, 0, True],
    "FRANCE": [1, 0, True],
    "GABON": [1, 0, False],
    "GEORGIA": [4, 0, False],
    "GERMANY": [1, 0, True],
    "GHANA": [0, 0, False],
    "GREECE": [2, 0, True],
    "GUATEMALA": [-6, 0, False],
    "GUINEA": [0, 0, False],
    "HAITI": [-5, 0, True],
    "HONDURAS": [-6, 0, False],
    "HUNGARY": [1, 0, True],
    "ICELAND": [0, 0, False],
    "INDIA": [5, 30, False],
    "INDONESIA": [7, 0, False],
    "IRAN": [3, 30, False],
    "IRAQ": [3, 0, False],
    "IRELAND": [0, 0, True],
    "ISRAEL": [2, 0, True],
    "ITALY": [1, 0, True],
    "IVORY COAST": [0, 0, False],
    "JAMAICA": [-5, 0, False],
    "JAPAN": [9, 0, False],
    "JORDAN": [2, 0, True],
    "KAZAKHSTAN": [6, 0, False],
    "KENYA": [3, 0, False],
    "KOSOVO": [1, 0, True],
    "KUWAIT": [3, 0, False],
    "KYRGYZSTAN": [6, 0, False],
    "LAOS": [7, 0, False],
    "LATVIA": [2, 0, True],
    "LEBANON": [2, 0, True],
    "LESOTHO": [2, 0, False],
    "LIBERIA": [0, 0, False],
    "LIBYA": [2, 0, False],
    "LIECHTENSTEIN": [1, 0, True],
    "LITHUANIA": [2, 0, True],
    "LUXEMBOURG": [1, 0, True],
    "MADAGASCAR": [3, 0, False],
    "MALAWI": [2, 0, False],
    "MALAYSIA": [8, 0, False],
    "MALDIVES": [5, 0, False],
    "MALI": [0, 0, False],
    "MALTA": [1, 0, True],
    "MAURITANIA": [0, 0, False],
    "MAURITIUS": [4, 0, False],
    "MEXICO": [-6, 0, True],
    "MOLDOVA": [2, 0, True],
    "MONACO": [1, 0, True],
    "MONGOLIA": [8, 0, False],
    "MONTENEGRO": [1, 0, True],
    "MOROCCO": [0, 0, True],
    "MOZAMBIQUE": [2, 0, False],
    "MYANMAR": [6, 30, False],
    "NAMIBIA": [2, 0, False],
    "NEPAL": [5, 45, False],
    "NETHERLANDS": [1, 0, True],
    "NEW ZEALAND": [12, 0, True],
    "NICARAGUA": [-6, 0, False],
    "NIGER": [1, 0, False],
    "NIGERIA": [1, 0, False],
    "NORTH KOREA": [9, 0, False],
    "NORTH MACEDONIA": [1, 0, True],
    "NORWAY": [1, 0, True],
    "OMAN": [4, 0, False],
    "PAKISTAN": [5, 0, False],
    "PALESTINE": [2, 0, True],
    "PANAMA": [-5, 0, False],
    "PAPUA NEW GUINEA": [10, 0, False],
    "PARAGUAY": [-4, 0, True],
    "PERU": [-5, 0, False],
    "PHILIPPINES": [8, 0, False],
    "POLAND": [1, 0, True],
    "PORTUGAL": [0, 0, True],
    "QATAR": [3, 0, False],
    "ROMANIA": [2, 0, True],
    "RUSSIA": [3, 0, False],
    "RWANDA": [2, 0, False],
    "SAUDI ARABIA": [3, 0, False],
    "SENEGAL": [0, 0, False],
    "SERBIA": [1, 0, True],
    "SEYCHELLES": [4, 0, False],
    "SIERRA LEONE": [0, 0, False],
    "SINGAPORE": [8, 0, False],
    "SLOVAKIA": [1, 0, True],
    "SLOVENIA": [1, 0, True],
    "SOMALIA": [3, 0, False],
    "SOUTH AFRICA": [2, 0, False],
    "SOUTH KOREA": [9, 0, False],
    "SPAIN": [1, 0, True],
    "SRI LANKA": [5, 30, False],
    "SUDAN": [2, 0, False],
    "SWEDEN": [1, 0, True],
    "SWITZERLAND": [1, 0, True],
    "SYRIA": [2, 0, True],
    "TAIWAN": [8, 0, False],
    "TAJIKISTAN": [5, 0, False],
    "TANZANIA": [3, 0, False],
    "THAILAND": [7, 0, False],
    "TOGO": [0, 0, False],
    "TRINIDAD AND TOBAGO": [-4, 0, False],
    "TUNISIA": [1, 0, False],
    "TURKEY": [3, 0, False],
    "TURKMENISTAN": [5, 0, False],
    "UGANDA": [3, 0, False],
    "UKRAINE": [2, 0, True],
    "UNITED ARAB EMIRATES": [4, 0, False],
    "UNITED KINGDOM": [0, 0, True],
    "UNITED STATES": [-5, 0, True],
    "URUGUAY": [-3, 0, False],
    "UZBEKISTAN": [5, 0, False],
    "VENEZUELA": [-4, 0, False],
    "VIETNAM": [7, 0, False],
    "YEMEN": [3, 0, False],
    "ZAMBIA": [2, 0, False],
    "ZIMBABWE": [2, 0, False],
}
